### ISSUE TITLE
blue->bluert

### ISSUE THREAD

**Issue by ghhgfhrt** [luka-group/Lattice#10]
Excuse me, how does the evaluation index blue in your article become the full version of bluet to upgrade to the evaluation index value in your article?

**Comment by FeiWang96** [comment]
If you are asking how to compute BLEURT scores, please refer to [this link](https://github.com/google-research/language/tree/master/language/totto#computing-the-bleurt-score).

**Comment by ghhgfhrt** [comment]
Excuse me, I'm following your link to configure bluert with have run the configuration command pip3 install -r language/totto/eval_requirements.txt and succeeded, but when I run the script I get the error Failed to run python script. please Please ensure that all libraries are installed and that files are formatted correctly.

**Comment by ghhgfhrt** [comment]
Thank you for your answer, I would like to inquire about the bash language/totto/tottoo_eval.sh --prediction_path language/totto/sample/output_sample.txt ---target_path language/totto/ sample/dev_sample.jsonl --bleurt_ckpt <BLEURT checkpoint path> What should be the addresses of prediction_path and target_path in the Lattice project for this script command?

**Comment by FeiWang96** [comment]
prediction_path: outputs/generated_predictions.txt
target_path: totto_data/totto_dev_data.jsonl

Note that gold references for the test set are held out. You'll need to submit the prediction file to the official leaderboard to get the scores.
