### ISSUE TITLE
Question about type_edges in structural attention

### ISSUE THREAD

**Issue by cws7777** [luka-group/Lattice#2]
Hi!
First of all, thank you for the great work!

I have a quick question about type_edges that you added in structural attention.
Is `type_edges` fixed as `((1, 1), (2, 2), (1, 2), (2, 1), (3, 1), (3, 2), (1, 3), (2, 3))`?
If it is, then why?
If it is not, then where can I find type_edge values of each input?

Thank you!
Hope you have a great one!

Best,
Paul

**Comment by FeiWang96** [comment]
Hi Paul,

> First of all, thank you for the great work!

Thank you!

> Is type_edges fixed?

Yes.

> If it is, then why?

We use `type_edges` to create the attention mask based on token types. `(a,b)` means there are attention flows from `a` to `b`. As written in the docstring, we assign `1`&`2` for metadata tokens and `3` for cell tokens. (We assign type ids during [preprocessing](https://github.com/luka-group/Lattice/blob/main/preprocess/table_linearization.py).) So the default `type_edges` will mask attention flows between all cell tokens. And the attention between cell tokens in the same row/column is [unmasked later](https://github.com/luka-group/Lattice/blob/e80cbaaa8ca1be4d7a08b35ba86f68da27dd95f1/model/structural_attention.py#L30).

Best regards,
Fei

**Comment by cws7777** [comment]
Thank you for kindly answering my question! :)

I have one more quick question.
Does each value of type_ids, row_ids and col_ids indicate each token or each character of tokens?
It seems counting all of the characters of text (one of type_ids in train.csv has `1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~~`).
Am I understanding correctly?


Thank you once again! :)

Hope you have a great one!

Best,
Paul

**Comment by FeiWang96** [comment]
Hi Paul,


Yes, in `train.csv`, type_ids, row_ids, and col_ids are character-level, which are assigned during [preprocessing](https://github.com/luka-group/Lattice/blob/e80cbaaa8ca1be4d7a08b35ba86f68da27dd95f1/preprocess/table_linearization.py#L27).
These character-level ids are then mapped to token-level [after tokenization](https://github.com/luka-group/Lattice/blob/e80cbaaa8ca1be4d7a08b35ba86f68da27dd95f1/train.py#L364) at the beginning of training.

Best regards,
Fei

**Comment by cws7777** [comment]
Thank you for quick response! :)
Also, if there are two token types (type_ids), then should `type_edge` also be changed like `((1, 1), (2, 2), (1, 2), (2, 1))`?
This might be depended on the what type_ids are, but I'm just asking!

I'm new to this kind of task with using PLMs.

Sorry for bothering and thank you once again for your kindness!

Best,
Paul

**Comment by FeiWang96** [comment]
Hi Paul,

If you want to construct a complete attention flow, then yes. You can use `type_edge` to mask any specific attention flow from one type of nodes to another type of nodes.

Best regards,
Fei

**Comment by cws7777** [comment]
Thank you!
Hope you have a great one! :)

Best,
Paul

**Comment by cws7777** [comment]
Hi Fei!
I have a quick question for your ablation study.
If I want to run the experiment that uses only structure-aware self-attention, then should I just take out [compute_invariant_bias function](https://github.com/luka-group/Lattice/blob/e80cbaaa8ca1be4d7a08b35ba86f68da27dd95f1/model/modeling_t5.py#L408) in modeling_t5.py?

Thanks!
Hope you have a good one!

Best,
Paul

**Comment by cws7777** [comment]
Can you please answer the above question?
And is there a purpose for assigning the ids with character-level? Can we just assign those ids as token-level directly?
Thank you! :)

Best regards,
Paul
