### ISSUE TITLE
Current requirements.txt generate a version error when importing transformers

### ISSUE THREAD

**Issue by dafraile** [luka-group/Lattice#3]
Hi, I tried to install this in a conda environment and when running with the current requirements.txt file generates an error when importing transformers (due to a mismatch of installed packages. I resolved it by removing the versions from all transformers-related packages and installing currently last versions:

transformers==4.25.1
datasets==2.7.1
sentencepiece==0.1.97

I suggest you to update the requirements file so it can be installed and run properly

Cheers,

David

**Comment by FeiWang96** [comment]
Hi David,

Thanks for your suggestion. We've updated the requirements.

Best,
Fei
