### ISSUE TITLE
Have you got this kind of message?

### ISSUE THREAD

**Issue by cws7777** [luka-group/Lattice#4]
Hi, 
I got below message when I run `bash run.sh`
![image](https://user-images.githubusercontent.com/12144129/207495089-c76754d0-093a-4c91-a26f-114f822794b0.png)

Have you got this kind of message when you run `bash run.sh`? 
Estimation Time gives me like 300 hours to run..?

Thanks

Best regards,
Paul

**Comment by FeiWang96** [comment]
> Have you got this kind of message when you run bash run.sh?

No worry. It won't cause deadlocks.

> Estimation Time gives me like 300 hours to run..?

It depends on your hyperparameters and hardware.
