### ISSUE TITLE
About Hitab associated codes

### ISSUE THREAD

**Issue by zhangbin1997** [luka-group/Lattice#5]
Dear author, I have only seen the codes related to Totto, but where are the codes related to HiTab? Can you provide the codes like Totto, or do I need to replace the pre-trained model structure in the HiTab github myself. Looking forward to your reply, thank you.

**Comment by FeiWang96** [comment]
Hi. Despite the model structure, you also need to convert the data to our format. Specifically, the inputs should have `row_ids`, `col_ids`, and `type_ids`. The linearization process of HiTab is slightly different from the [table_linearization.py](https://github.com/luka-group/Lattice/blob/main/preprocess/table_linearization.py) of ToTTo as described in section 3.1 of our [paper](https://arxiv.org/pdf/2205.03972.pdf). Please check the corresponding code and paper for more details.

**Comment by zhangbin1997** [comment]
em, I know the difference between Totto and Hitab.  By the way, are you not going to open source HiTab dataset processing scripts？

**Comment by FeiWang96** [comment]
We don't think it is necessary since the preprocessing code is easy to implement. But let us know if you encounter any problem.
