### ISSUE TITLE
About Hitab best checkpoint

### ISSUE THREAD

**Issue by zhangbin1997** [luka-group/Lattice#6]
hi，i know in your code，it will choose the best checkpoint for evaluation in Totto.  And because you don't open source the HiTab code, i reproduce the HiTab github's code, but in HiTab github, its defalut setting is choosing the last checkpoint for evaluation, and i wanna know the way you do in HiTab dataset, thanks ~

**Comment by FeiWang96** [comment]
Hi,

Baselines in the HiTab repo also select the [best checkpoint](https://github.com/microsoft/HiTab/blob/12f8d139100962817062c91b282eecc6094163a6/data2text/experiment/train_d2t.py#L39). Note that we both use the trainer in [huggingface/transformers](https://github.com/huggingface/transformers). Selecting the best-performing checkpoint on the development set is a common setting.

I'd like to mention that we've released all the essential code with the ToTTo dataset as an example. You can easily extend our code to other datasets.
